# Generated by Django 4.2.7 on 2025-11-22 05:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('predicted_class', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('all_probabilities', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=50)),
                ('base_model', models.CharField(blank=True, max_length=50)),
                ('epochs', models.IntegerField()),
                ('final_accuracy', models.FloatField(blank=True, null=True)),
                ('final_loss', models.FloatField(blank=True, null=True)),
                ('training_time', models.DurationField(blank=True, null=True)),
                ('model_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
